foxglove/ws-protocol

- README.md
- docs/spec.md
- python/src/server.py
- typescript/src/FoxgloveClient.ts
Import spec from google doc, along with some updates and reformatting
> Add spec doc, update README

- cpp/.clang-format
- cpp/.gitignore
- cpp/CMakeLists.txt
- cpp/LICENSE
- cpp/Makefile
- cpp/README.md
- cpp/cmake/conan.cmake
- cpp/codecov.yml
- cpp/conanfile.py
- cpp/include/foxsocketpp.hpp
- cpp/include/foxsocketpp/message_defs.hpp
- cpp/include/foxsocketpp/rosmsg.hpp
- cpp/include/foxsocketpp/version.hpp
- cpp/scripts/coverage.sh
- cpp/scripts/format.sh
- cpp/src/foxsocketpp.cpp
- cpp/src/main.cpp
- cpp/src/rosmsg.cpp
- cpp/test/test.cpp
A skeleton of a C++ websocket server. This is (currently) a concrete implementation that compiles to an executable, not a library meant for reuse in other applications. In that vein, it includes ROS1 serialization code so it can publish topics that Studio will be able to understand both encoding-wise and semantically.
> Add C++ skeleton

- .github/workflows/ci.yml
- .gitignore
- Pipfile
- Pipfile.lock
- README.md
- typescript/.yarnrc
Published as `foxglove-websocket==0.0.1`
> Publish Python package to PyPI

- python/README.md
- python/scripts/example.py
- python/setup.cfg
- python/src/foxglove_websocket/server.py
- Adds README specific to the Python package
- Renames `handle_message` to `send_message`
> Add README for python package on PyPI

- .vscode/settings.json
- typescript/package.json
- typescript/src/FoxgloveServer.test.ts
- typescript/src/FoxgloveServer.ts
- typescript/src/index.test.ts
- typescript/src/index.ts
- yarn.lock
Initial empty `advertise` message is not sent to new clients if there are no channels advertised.
Adds initial unit tests for TS server
> Add unit tests for TypeScript server

- README.md
- python/README.md
- typescript/README.md
- typescript/package.json
Adds documentation for the JS/TS package. Updates the build setting to include CommonJS module output in the built package as well as ESM.
> Add README for TypeScript package and build cjs module

- python/README.md
- python/setup.cfg
- python/src/foxglove_websocket/examples/simple_server.py
- python/src/foxglove_websocket/server.py
Fixes issues where the Python server would crash when clients connected or disconnected in the middle of a message send operation.
Fixes https://github.com/foxglove/ws-protocol/issues/16
> Fix ConnectionClosed errors and mutation during iteration in Python server

- typescript/ws-protocol-examples/README.md
- typescript/ws-protocol-examples/package.json
- typescript/ws-protocol-examples/src/boxen.ts
- typescript/ws-protocol-examples/src/examples/image-server.ts
- typescript/ws-protocol-examples/src/examples/sysmon.ts
- yarn.lock
> fix typo in readme, add studio url to console output

- README.md
- python/README.md
A couple more cleanups from #24.
> Small readme cleanups

- cpp/Makefile
- cpp/docker-compose.yml
- cpp/examples/example_server.cpp
- cpp/foxglove-websocket/conanfile.py
- cpp/foxglove-websocket/include/foxglove/websocket/server.hpp
A couple of API and build improvements.
> cpp: Add removeChannel, missing include, operator==

- python/pyproject.toml
- python/tests/test_server.py
None
Add a failing test for the issue reported in #41.
> Python sever: add failing test for unsubscribe during send

- .github/workflows/ci.yml
- Pipfile
- Pipfile.lock
- python/pyproject.toml
> Upgrade pipenv

- typescript/ws-protocol-examples/package.json
- typescript/ws-protocol-examples/src/examples/mcap-play.ts
- yarn.lock
Upgrades @mcap/core to get the fix from https://github.com/foxglove/mcap/pull/597
> TypeScript ws-protocol-examples v0.0.8; bump @mcap/core

- .vscode/settings.json
- typescript/ws-protocol/src/FoxgloveClient.ts
- typescript/ws-protocol/src/FoxgloveServer.test.ts
- typescript/ws-protocol/src/FoxgloveServer.ts
- typescript/ws-protocol/src/types.ts
- TypeScript client and server support for client-advertised topics and client-published messages
> Implement client publishing in the TypeScript client and server

- typescript/ws-protocol-examples/package.json
Added minimum NodeJS version requirement for `npx @foxglove/ws-protocol-examples`
A user reported an error using an old version of Node.
> Add minimum nodejs version requirement

- Pipfile.lock
- python/setup.cfg
Add minimum version to `protobuf` dependency for `foxglove-websocket[examples]`
Fixes #310
Fixes FG-1005
> python examples: add min version to protobuf dependency

- typescript/ws-protocol-examples/package.json
- typescript/ws-protocol-examples/src/examples/param-client.ts
- typescript/ws-protocol-examples/src/examples/param-server.ts
- typescript/ws-protocol-examples/src/index.ts
- typescript/ws-protocol/package.json
- typescript/ws-protocol/src/FoxgloveClient.ts
- typescript/ws-protocol/src/FoxgloveServer.test.ts
- typescript/ws-protocol/src/FoxgloveServer.ts
- typescript/ws-protocol/src/types.ts
- Add parameter support to the typescript implementation
Adds support for parameters (see #288) to the typescript package
> Add parameter support to the typescript implementation

- typescript/ws-protocol/src/FoxgloveClient.ts
None
Minor type corrections related to client publications
> typescript: Minor type corrections

- typescript/ws-protocol/package.json
- None
- Bumps version of @foxglove/ws-protocol
> Bump version of @foxglove/ws-protocol

- typescript/ws-protocol-examples/package.json
- typescript/ws-protocol/package.json
- typescript/ws-protocol/src/FoxgloveServer.ts
- typescript/ws-protocol/src/types.ts
- yarn.lock
Fixed an incompatibility with `@types/ws@8.5.4`
Fixes #330
Fixes FG-1311
See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63627
> Upgrade @types/ws and remove incorrect Blob usage from TS server

- docs/spec.md
Updated specification with information about supported encodings in Studio.
Partially addresses FG-906
See also: https://github.com/foxglove/website/pull/938
> Add notes about valid encodings with link to studio docs

- typescript/ws-protocol/package.json
- typescript/ws-protocol/src/FoxgloveClient.ts
- typescript/ws-protocol/src/FoxgloveServer.test.ts
- typescript/ws-protocol/src/FoxgloveServer.ts
- typescript/ws-protocol/src/parse.ts
- typescript/ws-protocol/src/types.ts
- Updates `@foxglove/ws-protocol` to implement service operations added in #344 
- Updates `@foxglove/ws-protocol` to implement service operations added in #344 
- Minor cleanup in the way client messages are being handled
> @foxglove/ws-protocol: Add services capability, minor cleanup

- typescript/ws-protocol/src/FoxgloveServer.test.ts
- typescript/ws-protocol/src/FoxgloveServer.ts
- typescript/ws-protocol/src/types.ts
- @foxglove/ws-protocol: Add support for sessionId field
See title
> @foxglove/ws-protocol: Add support for sessionId field

- docs/spec.md
- typescript/ws-protocol/src/FoxgloveServer.test.ts
- typescript/ws-protocol/src/types.ts
- Allow unsetting (removing) parameters
See https://github.com/foxglove/studio/pull/5227#discussion_r1087356472 
Fixes #346
> Allow unsetting (removing) parameters

- docs/spec.md
- typescript/ws-protocol/package.json
- typescript/ws-protocol/src/FoxgloveClient.ts
- typescript/ws-protocol/src/FoxgloveServer.ts
- typescript/ws-protocol/src/types.ts
- Adds a new capability to subscribe to connection graph updates which includes information about topic publishers/subscribers as well as service providers
See above
> spec: Add connection graph capability

- typescript/ws-protocol-examples/package.json
- typescript/ws-protocol/package.json
None
- Bumps @foxglove/ws-protocol
- Updates version used in @foxglove/ws-protocol-examples
> Bump @foxglove/ws-protocol version

- typescript/ws-protocol-examples/package.json
None
Follow up of https://github.com/foxglove/ws-protocol/pull/387#discussion_r1129941700
> Bump @foxglove/ws-protocol-examples version

- README.md
- Update README.md to include mention of Eclipse eCAL bridge
- Update README.md to include mention of Eclipse eCAL bridge
> Update README.md to include mention of Eclipse eCAL bridge

- .github/workflows/ci.yml
- cpp/Makefile
- cpp/dev.Dockerfile
- cpp/foxglove-websocket/include/foxglove/websocket/websocket_server.hpp
- Fix c++20 incompatibility
Fixes #406
> Fix c++20 incompatibility

- cpp/foxglove-websocket/conanfile.py
> cpp: Use asio headers provided by websocketpp

- Pipfile.lock
- python/setup.cfg
- python/src/foxglove_websocket/examples/json_server.py
- python/src/foxglove_websocket/examples/param_server.py
- python/src/foxglove_websocket/examples/protobuf_server.py
- python/src/foxglove_websocket/examples/threaded_server/middleware.py
- python/src/foxglove_websocket/server/__init__.py
- python/src/foxglove_websocket/server/client_state.py
- python/src/foxglove_websocket/types.py
- python/tests/test_server.py
- Update python server API
Makes changes to the Python API:
- Updates additional fields in `serverInfo` message
- Adds `time` capability
- Adds `services` capability
- Adds `clientPublish` capability
- Adds `parameters` + `parametersSubscribe` capabilities
> Update python example implementation

- typescript/ws-protocol/package.json
None
TypeScript ws-protocol v0.7.0
> TypeScript ws-protocol v0.7.0

- typescript/ws-protocol-examples/package.json
- typescript/ws-protocol-examples/src/examples/publish-client.ts
None
Updates `@foxglove/ws-protocol-examples` to use the latest version of `@foxglove/ws-protocol`. Makes CI happy again.
> Use latest @foxglove/ws-protocol in examples pkg

- cpp/foxglove-websocket/include/foxglove/websocket/websocket_server.hpp
C++ implementation: Fix segfault due to invalid iterator
See https://github.com/foxglove/ros-foxglove-bridge/pull/251
> C++ implementation: Fix segfault due to invalid iterator

- cpp/foxglove-websocket/include/foxglove/websocket/websocket_server.hpp
C++: Fix specific exceptions not being caught, leading to vague error messages.
Fixes a minor regression introduced with #491
> C++: Fix specific exceptions not being caught

- typescript/ws-protocol/package.json
None
Bump `@foxglove/ws-protocol` to v0.7.1
> Bump @foxglove/ws-protocol to v0.7.1

- typescript/ws-protocol-examples/package.json
- typescript/ws-protocol-examples/src/examples/mcap-record.ts
- typescript/ws-protocol-examples/src/examples/perf-test-client.ts
- typescript/ws-protocol-examples/src/examples/publish-client.ts
- typescript/ws-protocol-examples/src/examples/service-client.ts
- typescript/ws-protocol/package.json
- typescript/ws-protocol/src/FoxgloveClient.ts
- typescript/ws-protocol/src/FoxgloveServer.test.ts
- typescript/ws-protocol/src/FoxgloveServer.ts
- typescript/ws-protocol/src/parse.ts
- yarn.lock
None
Basically does the same as https://github.com/foxglove/studio/pull/6724
> Upgrades typescript-eslint to v6, and uses the new @foxglove/eslint-plugin that's compatible with it.
> Upgrade typescript-eslint to v6

- .github/workflows/ci.yml
- .github/workflows/github-pages.yml
- typescript/test-client-web-app/.gitignore
- typescript/test-client-web-app/README.md
- typescript/test-client-web-app/package.json
- typescript/test-client-web-app/public/index.html
- typescript/test-client-web-app/public/robots.txt
- typescript/test-client-web-app/src/App.css
- typescript/test-client-web-app/src/App.tsx
- typescript/test-client-web-app/src/WorkerSocketAdapter.ts
- typescript/test-client-web-app/src/index.css
- typescript/test-client-web-app/src/index.tsx
- typescript/test-client-web-app/src/react-app-env.d.ts
- typescript/test-client-web-app/src/worker.js
- typescript/test-client-web-app/tsconfig.json
- typescript/test-client-web-app/webpack.config.js
- yarn.lock
Adds a web app for testing ws-protocol compliant server implementations
This web app will be available at https://foxglove.github.io/ws-protocol
> Add web app for testing ws-protocol server implementations

- .github/workflows/github-pages.yml
None
Fixes wrong directory name (directory changed in #577)
> Fix github-pages job

- typescript/ws-protocol/package.json
Release @foxglove/ws-protocol `v0.7.2`
> Release @foxglove/ws-protocol `v0.7.2`

- typescript/ws-protocol-examples/src/examples/image-server.ts
Update image-server to latest pureimage api
Was raising errors when running the examples.
> Update image-server to latest pureimage api

- cpp/foxglove-websocket/conanfile.py
None
Fixes CI build errors for the C++ examples
> Fix c++ examples CI build error

- .github/workflows/ci.yml
> ci.yml: PyPI uses OIDC for auth

- cpp/README.md
No code changes. Updated documentation for c++ implementation of foxglove websocket.
- Document thread safety and message latching use case example
> Document thread safety and message latching use case example

- typescript/ws-protocol-examples/src/examples/perf-test-client.ts
None
Fixes lint errors in https://github.com/foxglove/ws-protocol/pull/656
> Remove unnecessary template literal

- typescript/ws-protocol-examples/package.json
> Bump ws-protocol-examples to v0.7.1

- typescript/ws-protocol-examples/package.json
`mcap-record`: Avoid potential channel duplication (#744)
None
> TypeScript ws-protocol-examples v0.8.1

- typescript/ws-protocol/package.json
None
None
Bump @foxglove/ws-protocol to 0.7.4
Includes #783
> Bump @foxglove/ws-protocol to 0.7.4

- typescript/ws-protocol-examples/package.json
- typescript/ws-protocol-examples/src/examples/service-server.ts
None
None
- Bumps the `@foxglove/ws-protocol` dependency
- Reverts accidentally committed change (from #783)
> @foxglove/ws-protocol-examples: Bump ws-protocol dependency, cleanup service server

- .github/workflows/dependabot.yml
None
None
Auto-approve and merge dependabot PRs.
> Add workflow to approve dependabot PRs

- typescript/ws-protocol-examples/package.json
https://github.com/foxglove/ws-protocol/commits/main/typescript/ws-protocol-examples?since=2024-06-18&until=2025-01-26
> @foxglove/ws-protocol-examples v0.9.0

- test-client-web-app/package.json
- typescript/ws-protocol-examples/package.json
- typescript/ws-protocol/package.json
> Bump `@foxglove/ws-protocol` to 0.8.0, `@foxglove/ws-protocol-examples` to 0.10.0
