foxglove/ws-protocol

.vscode/settings.json
python/pyproject.toml
python/src/foxglove_websocket/server.py
python/tests/test_server.py

Adds `server.set_listener()` to allow user code to handle subscribe/unsubscribe events.

python: add server listener for subscribe/unsubscribe callbacks

---

typescript/scripts/example.ts
typescript/src/FoxgloveClient.ts
typescript/src/parse.ts
typescript/src/types.ts

In order to reuse parsed descriptors for deserialization and other purposes, Studio needs to be in control of its descriptor cache. The logic embedded in this client was making that difficult. The client API is now more similar to the actual protocol.

Remove subscription and createDeserializer logic from TS client

---

python/src/foxglove_websocket/server.py
python/src/foxglove_websocket/types.py
python/tests/test_server.py

Python server now translates add_channel/remove_channel to advertise/unadvertise messages. Previously the channel list was only sent once to new clients upon connection.

Publish added/removed channels to clients after first connection

---

README.md
typescript/ws-protocol-examples/README.md
typescript/ws-protocol/README.md

Ensures the user always gets the latest version of the example scripts. By default npx might use an old version that's cached.

Add `@latest` to all npx commands

---

typescript/ws-protocol-examples/README.md
typescript/ws-protocol-examples/package.json
typescript/ws-protocol-examples/src/examples/image-server.ts
typescript/ws-protocol-examples/src/examples/simple-client.ts

`npx @foxglove/ws-protocol-examples simple-client` now supports JSON-encoded messages.
Closes https://github.com/foxglove/ws-protocol/issues/31

Add json decoding support to TypeScript simple-client example

---

python/pyproject.toml
python/src/foxglove_websocket/server/__init__.py
python/src/foxglove_websocket/server/client_state.py
python/tests/test_client_state.py
python/tests/test_server.py

Fixed a crash in `send_message()` that could occur under load due to a race condition.
Fixes https://github.com/foxglove/ws-protocol/issues/41. The race condition stemmed from mutation of `subscriptions_by_channel` during `await`. This would happen if channels were removed or if clients subscribed/unsubscribed while the server was waiting to send a message. To fix the race, the mutable data structures are replaced with immutable dicts (MappingProxyTypes), rather than copy them during each `send_message` call, since `send_message` is expected to be the most frequent API call.

Python server: fix race condition with mutation of client state

---

.github/dependabot.yml

None
Dependabot seems to handle upgrading sub-packages when it is pointed to the repo root, so we get duplicate PRs by also pointing it at the workspace packages.

Don't point dependabot at specific workspace packages

---

.github/workflows/ci.yml

**Public-facing changes**
None
Skip running TestPyPI CI step on PRs from forks, since the auth token will not be available.
Same fix as https://github.com/foxglove/mcap/pull/358

Don't run TestPyPI CI step on forks

---

python/src/foxglove_websocket/examples/protobuf_server.py

Clarified protoc invocation for generating the FileDescriptorSet.
Although `--include_imports` is not necessary for the example code, it is necessary for Foxglove schemas and other custom schemas that import types from other proto files.

Add --include_imports to protoc invocation

---

.github/workflows/ci.yml

Skip TestPyPI on dependabot PRs, since dependabot does not have access to the TestPyPI secret

skip TestPyPI for dependabot PRs

---

docs/spec.md

Extend the spec with ability to send data from client to server.
This PR adds 3 new operations to the spec to allow sending data from the client to the server. Once we have agreed on the spec, I will update the example server implementation accordingly.
Partially fixes #38 
Partially supersedes #158

Extend spec with ability to send data from client to server.

---

python/README.md

zsh (the default shell on MacOS) needs backslashes to be escaped or the argument to be quoted, see e.g.: https://stackoverflow.com/a/30539963/5087436

python readme: string literal for [examples]

---

typescript/ws-protocol-examples/package.json

Added Node.js max version to `npx @foxglove/ws-protocol-examples`.
Node 18 is not currently supported due to https://github.com/cruise-automation/wasm-lz4/issues/8 & https://github.com/foxglove/wasm-bz2/issues/4

Add Node max version

---

cpp/examples/example_server.cpp

Fixed a base64 encoding issue in the C++ example_server.
Fixes https://github.com/foxglove/ws-protocol/issues/278

Fix base64 encoding when char is signed

---

typescript/ws-protocol-examples/package.json
typescript/ws-protocol-examples/src/examples/publish-client.ts
yarn.lock

- `publish-client` now supports "cdr" encoding (advertise and publish to ROS 2)

Add "cdr" (ROS 2) support to publish-client

---

typescript/ws-protocol-examples/src/examples/publish-client.ts

None
This patch fixes a small bug in the `publish-client` example. We first have to wait until the websocket connection is established before we can publish messages over it

publish-client example: Make sure connection is established

---

docs/spec.md

Extend spec with parameter support
Adds the following new capabilities to the spec
- `parameters`: Allow clients to get & set parameters
- `parameterSubscribe`: Allow clients to subscribe to parameter changes

Extend spec with parameter support

---

docs/spec.md
typescript/ws-protocol/src/FoxgloveClient.ts
typescript/ws-protocol/src/FoxgloveServer.test.ts
typescript/ws-protocol/src/FoxgloveServer.ts
typescript/ws-protocol/src/parse.ts
typescript/ws-protocol/src/types.ts

- Allow server to publish time data (binary)
- Adapt typescript client/server accordingly
- Extends the spec by adding publishing of time data under a new opcode (0x02). By publishing time data, clients can be informed about the progress of time even if no other message data is published.
- Updates `@foxglove/ws-protocol` accordingly
Supersedes #298

Extend spec with publishing time data

---

.github/workflows/ci.yml

- None
This CI step takes more time than it saves. It appears to spend 6+ minutes saving ~2 minutes.

Disable action-docker-layer-caching in CI (2x CI speedup)

---

typescript/ws-protocol-examples/src/examples/param-server.ts
typescript/ws-protocol/src/FoxgloveServer.test.ts
typescript/ws-protocol/src/FoxgloveServer.ts

- Allow to configure capabilities in typescript server implementation
So far, capabilities of the typescript server implementation were hardcoded. With this PR, capabilities can be configured via a constructor argument. See also https://github.com/foxglove/ws-protocol/pull/319#discussion_r1062854374

Allow to configure capabilities in typescript server implementation

---

docs/spec.md
typescript/ws-protocol-examples/src/examples/param-server.ts
typescript/ws-protocol/src/FoxgloveClient.ts
typescript/ws-protocol/src/FoxgloveServer.test.ts
typescript/ws-protocol/src/FoxgloveServer.ts
typescript/ws-protocol/src/types.ts

- Allow specifying a request id in the `setParameters` operation
The server may reject requests to update parameters for various reasons such as e.g. parameters being readonly. To allow a client to verify if parameter updates were successful, this PR adds an optional request ID field to the `setParameters` operation.

Allow specifying a request id when setting parameters

---

docs/spec.md
typescript/ws-protocol/src/FoxgloveServer.test.ts
typescript/ws-protocol/src/FoxgloveServer.ts
typescript/ws-protocol/src/types.ts

-  Allow server to communicate supported encodings
A client currently has no way in determining which message encodings the server supports for client publishing. This PR adds a field to the `serverInfo` message which informs clients about supported encodings.

 Allow server to communicate supported encodings

---

.vscode/settings.json
typescript/ws-protocol-examples/package.json
typescript/ws-protocol-examples/src/examples/image-server.ts
typescript/ws-protocol-examples/src/examples/mcap-play.ts
typescript/ws-protocol-examples/src/examples/param-server.ts
typescript/ws-protocol-examples/src/examples/sysmon.ts
typescript/ws-protocol-examples/src/examples/util/setupSigintHandler.ts
typescript/ws-protocol/package.json
yarn.lock

Improved ^C exit behavior for `npx @foxglove/ws-protocol-examples`.
Updated TypeScript examples to use schemas from `@foxglove/schemas`.
Our server scripts weren't shutting down cleanly on sigint. I thought `ws.close()` would work, but for some unknown reason I had to manually `close()` each of the currently open clients as well. Additionally, Yarn 1 doesn't wait for the child process before it exits (https://github.com/yarnpkg/yarn/issues/4667) which is probably why I didn't notice the issue when originally creating these scripts.
Fixes #162

TS examples: use @foxglove/schemas; better sigint behavior

---

docs/spec.md
typescript/ws-protocol-examples/package.json
typescript/ws-protocol/package.json
typescript/ws-protocol/src/types.ts

- Allow to send additional server options to clients
Allows to inform clients about additional server options. E.g. for [foxglove-bridge  ](https://github.com/foxglove/ros-foxglove-bridge) we would like to communicate the ROS_DISTRO to the client

Spec: Allow to send additional metadata to clients

---

docs/spec.md

- Adds additional operations to allow clients to call services that are advertised by the server
Adds additional operations to allow clients to call services that are advertised by the server
FG-1456

Extend spec with services capability

---

.github/workflows/ci.yml
typescript/ws-protocol-examples/package.json
typescript/ws-protocol-examples/src/examples/mcap-play.ts
typescript/ws-protocol-examples/src/wasm-lz4.d.ts
yarn.lock

- ws-protocol-examples now run on nodejs 18.x
Switched from `wasm-lz4` to `@foxglove/wasm-lz4` to fix node 18.x compatibility

Switch lz4 dep to @foxglove/wasm-lz4, test on nodejs 16+18 in CI

---

docs/spec.md

- Adds optional `sessionId` field to `serverInfo` message
From #256:
> Including sessionId sent by server on opening connection allows client to understand context and if the connection is a re-connection from a dropped context, or if it is a new session connecting. We will then be able to clear state in the client when connecting to a new context, but retain state when reconnecting a dropped connection.
>
> Context: Customer is currently reconnecting to a websocket in a different context and the state is being preserved leading to incorrect results. They would like the state to be cleared when reconnecting to the WS in a new context.
Fixes #256
Linear: [FG-1654](https://linear.app/foxglove/issue/FG-1654/include-session-id-in-websocket-connection-% …

Spec: Add optional `sessionId` field to `serverInfo` message

---

typescript/ws-protocol-examples/src/examples/service-client.ts
typescript/ws-protocol-examples/src/examples/service-server.ts
typescript/ws-protocol-examples/src/index.ts
typescript/ws-protocol/package.json
typescript/ws-protocol/src/FoxgloveClient.ts

- `@foxglove/ws-protocol-examples`: Add example for calling services
- `@foxglove/ws-protocol`: Rename method `sendCallServiceRequest` -> `sendServiceCallRequest`
The service client is currently hardcoded to call the first `std_srvs/SetBool` advertised by the server.

Add example for calling services

---

typescript/ws-protocol-examples/src/examples/service-server.ts

None
Fixes CI errors that got introduced with #350 
My local linter tells me the exact opposite tho:
How can I bring CI and my local linter in line again? :thinking:

ws-protocol-examples: Fix include order

---

docs/spec.md

None
From #370:
> * [x] If you click on the link to "Message Data" in the TOC, it takes you to the client message data, not server message data.
> * [x] Additionally, the client message data op is listed under a heading called "JSON Messages". The heading called "Binary Messages" doesn't include the client message data.
> * [x] It looks like Service Call Request and Time have the same opcode (0x02).
It looks like that because it is currently not obvoius which messages are sent by the server and which by the client. In the TOC we divide between server and client messages, but the rest of the document does not since there it is divided into JSON and binary messages. IMO, the rest of the document and the heading order should be in the same order as …

Clean up specification

---

python/src/foxglove_websocket/server/__init__.py
python/src/foxglove_websocket/server/client_state.py
python/tests/test_client_state.py
typescript/ws-protocol/src/FoxgloveServer.ts

- Python / Typescript example implementation: Disallow multiple subscriptions per channel per client
The spec says that clients may only have one subscription for each channel at a time. However, our reference implementation allowed having more than one subscription. This PR fixes this for the following reference implementations:
fixes #233
fixes FG-957

Example server implementation: Disallow multiple client subscriptions per channel per client

---

docs/spec.md
typescript/ws-protocol/src/types.ts

- Add channel field `schemaEncoding` for advertise operation
Adds the optional channel field `schemaEncoding` which may be used if the schema encoding can't be uniquely deduced from the message encoding.
Example use case.
When message `encoding` is `cdr` (ROS 2), the schema can be specified using the `.msg` and `.idl` syntax.

Add channel field `schemaEncoding` for advertise operation

---

cpp/foxglove-websocket/CMakeLists.txt

None
I though that conan would automaticlaly do this, but apparently this is not the case: https://github.com/conan-io/conan-center-index/pull/16500#issuecomment-1463916745
Anyway, it's still a good practice to enable it explicitly in case it is build without conan

cpp: Explicitly enable cpp17

---

docs/spec.md
typescript/ws-protocol/src/types.ts

- Add optional parameter field `type`
Adds the optional field `type` to the Parameter struct for cases where the parameter type can't be deduced from the type of the `value` field alone.

Add parameter type name field to spec

---

typescript/ws-protocol-examples/README.md
typescript/ws-protocol-examples/package.json
typescript/ws-protocol-examples/src/examples/mcap-record.ts
typescript/ws-protocol-examples/src/index.ts

Added `npx @foxglove/ws-protocol-examples@latest mcap-record` which connects to a WebSocket server and records data into an MCAP file.

Add mcap-record example

---

docs/spec.md
typescript/ws-protocol/package.json
typescript/ws-protocol/src/types.ts

- Update allowed types for parameter values
Allows parameter values to be of type `{ [key: string]: ParameterValue }` or an array of that which can be the case for ROS1 parameters.

Update allowed types for parameter values

---

cpp/foxglove-websocket/include/foxglove/websocket/websocket_server.hpp

Correct calculation of removed topics and services while updating connection graph.
Now in websocket_server.hpp we have:
https://github.com/foxglove/ws-protocol/blob/5cdda39d9ed4e8287a5d27406f5e4f368bd0e1fc/cpp/foxglove-websocket/include/foxglove/websocket/websocket_server.hpp#L1158-L1159
And to find difference between them function set_difference is used:
https://github.com/foxglove/ws-protocol/blob/5cdda39d9ed4e8287a5d27406f5e4f368bd0e1fc/cpp/foxglove-websocket/include/foxglove/websocket/websocket_server.hpp#L1203-L1206
According to documentation of [std::set_difference](https://en.cppreference.com/w/cpp/algorithm/set_difference) it can be used only for sorted ranges (which is not a case when we use unorderd_set).
To have O(1) complexity for insert and search operations on …

Fix of incorrect using of set_difference in updateConnectionGraph function

---

python/setup.cfg
python/src/foxglove_websocket/server/__init__.py

- Python: Disable compression by default, allow specifying server kwargs
Allows specifying [websockets.server.serve(...) ](https://websockets.readthedocs.io/en/stable/reference/asyncio/server.html#websockets.server.serve)keyword arguments and disables compression (`compression=None`) by default
Fixes #443

Python: Disable compression by default, allow specifying server kwargs

---

docs/spec.md
typescript/ws-protocol/src/FoxgloveClient.ts
typescript/ws-protocol/src/FoxgloveServer.test.ts
typescript/ws-protocol/src/FoxgloveServer.ts
typescript/ws-protocol/src/parse.ts
typescript/ws-protocol/src/types.ts

- Extend spec to allow fetching of assets
Allows clients to request assets (files) from the server.
Example use case: Client requests mesh files which are referenced by a URDF

Extend spec to allow fetching of assets

---

.github/dependabot.yml

None
Adds a dependabot group to group eslint package updates together in one PR
From https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups:
> By default, Dependabot raises a single pull request for each dependency that needs to be updated to a newer version. You can use groups to create sets of dependencies (per package manager), so that Dependabot opens a single pull request to update multiple dependencies at the same time.

Add dependabot group for eslint packages

---

docs/spec.md
typescript/ws-protocol/src/types.ts

Add parameter type `float64` & `float64_array` for floating point values
Some languages, such as JavaScript, do not differentiate between integers and floating point numbers. The `float64` and `float64_array` types were added to avoid ambiguity by informing the client (or the server) that the value is a floating point number, or an array of it, respectively.
Example: When sending the following JSON via JS to the server, the server will receive the value `1` and deduce that the parameter is of type Integer.
```json
{
"op": "setParameters",
"parameters": [
{ "name": "/float_param", "value": 1.0 }
]
}
```
By adding `"type": "float64"`, the client can let the server know that the value should be treated as a 64-bit floating point number.
Related to FG-4486

Add parameter type `float64` & `float64_array` for floating point values

---

typescript/ws-protocol-examples/package.json

None
Use latest @foxglove/ws-protocol in examples, to make dependabot PRs work again

Use latest @foxglove/ws-protocol in examples

---

cpp/examples/src/example_server_flatbuffers.cpp
cpp/examples/src/example_server_protobuf.cpp
cpp/foxglove-websocket/CMakeLists.txt
cpp/foxglove-websocket/include/foxglove/websocket/server_factory.hpp
cpp/foxglove-websocket/src/server_factory.cpp

- Provide definition of `Server<Config>::setupTlsHandler()`
So far we did not provide the definition of `Server<Config>::setupTlsHandler()`, requiring the user to implement it themselves. This PR adds the `setupTlsHandler()` implementation taken from [foxglove_bridge](https://github.com/foxglove/ros-foxglove-bridge).
Fixes #540

Add server factory, provide definition of setupTlsHandler()

---

docs/spec.md

None
Addresses https://github.com/foxglove/ws-protocol/pull/519#issuecomment-1775641397

Improve documentation of parameter types

---

docs/spec.md

spec: Allow specifying service schema names & encodings
Allows for customization of service schema names and schema encodings.
Partially fixes https://github.com/foxglove/studio/issues/6970 
Partially resolves FG-5280

spec: Allow specifying service schema names & encodings

---

.github/workflows/github-pages.yml

None
`$default-branch` is not valid syntax in a workflow.
Also shortened the workflow name so it doesn't get truncated as much.

Fix GitHub Pages build

---

typescript/ws-protocol/src/FoxgloveServer.ts
typescript/ws-protocol/src/types.ts

@foxglove/ws-protocol: Update to spec changes
Adapts @foxglove/ws-protocol to the latest spec changes made in #563
Related to FG-5280

@foxglove/ws-protocol: Update to spec changes

---

typescript/ws-protocol-examples/package.json
typescript/ws-protocol-examples/src/examples/service-client.ts
typescript/ws-protocol-examples/src/examples/service-server.ts

Adapt typescript service examples to new spec
Uses the latest `advertiseService` spec update. Got slightly more complex but mainly due to an additional service endpoint being added.

Adapt typescript service examples to new spec

---

typescript/ws-protocol-examples/src/examples/mcap-play.ts

This conveys the schema encoding to the client allowing it to use the correct parser to handle the schema.

Add schemaEncoding to mcap-play channel registration

---

.vscode/settings.json
typescript/ws-protocol-examples/src/examples/mcap-play.ts

`mcap-play` now attempts to play messages using `log_time` against the wall clock. Previously it was playing messages as fast as possible regardless of the `log_time` between messages.

mcap-play: Play at wall speed

---

typescript/ws-protocol/src/FoxgloveServer.ts

None
Caught by a eslint upgrade in https://github.com/foxglove/ws-protocol/pull/652:
```
/home/runner/work/ws-protocol/ws-protocol/typescript/ws-protocol/src/FoxgloveServer.ts
Template literal expression is unnecessary and can be simplified  @typescript-eslint/no-useless-template-literals
```

Fix unnecessary template literal linting error

---

.vscode/settings.json
typescript/ws-protocol-examples/package.json

Fixed: `mcap-play` now plays at the correct speed instead of sending messages as fast as possible (#631)

Bump ws-protocol-examples to 0.7.0

---

cpp/foxglove-websocket/CMakeLists.txt
cpp/foxglove-websocket/include/foxglove/websocket/websocket_server.hpp

None
- Enables compiler warnings
- Fixes warnings identified by @jhurliman (requires `-Winconsistent-missing-destructor-override` and `-Wextra-semi-stmt`)

enable C++ compiler warnings

---

cpp/foxglove-websocket/include/foxglove/websocket/websocket_server.hpp

`Server::sendStatusAndLogMsg()` is now a public method, for sending status messages and errors/warnings to clients.
This method is useful for sending error messages to clients when an action fails, such as requesting an asset that doesn't exist.

Make Server::sendStatusAndLogMsg() public

---

README.md
docs/spec.md
python/README.md
python/setup.cfg
typescript/ws-protocol-examples/README.md
typescript/ws-protocol-examples/src/examples/image-server.ts
typescript/ws-protocol-examples/src/examples/mcap-play.ts
typescript/ws-protocol-examples/src/examples/param-server.ts
typescript/ws-protocol-examples/src/examples/service-server.ts
typescript/ws-protocol-examples/src/examples/sysmon.ts
typescript/ws-protocol/README.md
typescript/ws-protocol/package.json

- Update links from `studio.foxglove.dev` to `app.foxglove.dev`
- Update docs links from `foxglove.dev/docs` to `docs.foxglove.dev`
- Update references from "Studio" to "Foxglove"

Update studio links

---

cpp/foxglove-websocket/include/foxglove/websocket/common.hpp
cpp/foxglove-websocket/include/foxglove/websocket/serialization.hpp
cpp/foxglove-websocket/include/foxglove/websocket/websocket_server.hpp
cpp/foxglove-websocket/src/serialization.cpp
python/src/foxglove_websocket/examples/json_server.py
python/src/foxglove_websocket/server/__init__.py
python/src/foxglove_websocket/types.py
python/tests/test_server.py

Apply changes wrt. service definition to example server implementations

apply spec updates to c++ server implementation

---

cpp/examples/src/example_server_flatbuffers.cpp
cpp/examples/src/example_server_protobuf.cpp

None
Changes the log message in the cpp example server's subscribe/unsubscribe handlers to take into account the client id.
Fixes #688

Change log message in cpp example server subscribe handlers

---

.github/workflows/ci.yml
.gitignore

None
This adds a provenance attestation to the published package so consumers can verify that the package was built on GitHub Actions:
- https://github.blog/2023-04-19-introducing-npm-package-provenance/
- https://docs.npmjs.com/generating-provenance-statements#publishing-packages-with-provenance-via-github-actions
The package will appear like this on npm:
Also fixes an [error when publishing](https://github.com/foxglove/ws-protocol/actions/runs/8197963504/job/22420730354) due to trying to publish the same package twice (with different node versions).

Add provenance attestation when publishing to NPM

---

docs/spec.md
python/setup.cfg
typescript/ws-protocol-examples/src/examples/service-client.ts
typescript/ws-protocol/src/FoxgloveClient.ts
typescript/ws-protocol/src/types.ts

Add operation `serviceCallFailure` to communicate failure of calling a service
The current spec lacks a way to communicate the failure of calling a service. This PR changes that by adding a new operation which serves that purpose.

Add operation `serviceCallFailure` to communicate failure of calling a service

---

typescript/ws-protocol-examples/src/examples/service-server.ts
typescript/ws-protocol/src/FoxgloveServer.ts

Typescript: Add function `sendServiceCallFailure` to send service call failure to client
Forgot to add that in #733

typescript: Add sendServiceCallFailure to server impl

---

typescript/ws-protocol/package.json

TypeScript ws-protocol v0.7.3 Release
Includes #733, #735 and several dependabot PRs

TypeScript ws-protocol v0.7.3

---

typescript/ws-protocol/src/FoxgloveClient.ts

EventEmitter always emits values of `Error` types on "error", not `undefined`.
According to [the documentation of ws module for Node.js](https://github.com/websockets/ws/blob/HEAD/doc/ws.md#event-error), onerror handler emits `Error` types.
However, WebSocket in the browser does not emits `event.error`. This behavior is incorrect as per the code below.
https://github.com/foxglove/ws-protocol/blob/736c8dfc9256453a7ac017a823f308fd580571d2/typescript/ws-protocol/src/FoxgloveClient.ts#L29
I fixed to always emits values of `Error` types on "error".

Fix onerror handler

---

typescript/ws-protocol-examples/package.json
typescript/ws-protocol-examples/src/examples/mcap-record.ts
yarn.lock

The `mcap-record` command supports new options for customizing `--chunk-size` and `--compression-level`. The default compression level is lower, and the default chunk size is higher, which improves the ability to record high-frequency data.
Self-documenting via `--help` :)
The default compression level was quite high and was slowing down the recording process.

mcap-record: chunk size and compression options

---

typescript/ws-protocol-examples/src/examples/mcap-record.ts

Fix `mcap-record` creating duplicated channels if existing channels are re-advertised by the server
None
Logs a message when the server erroneously re-advertises channels which have been advertised before. As per the [spec](https://github.com/foxglove/ws-protocol/blob/main/docs/spec.md#advertise), only new channels should be advertised by the server but unfortunately not all servers comply with that. This extra check makes sure that channels are not duplicated in the resulting MCAP file.

mcap-record: Avoid duplicate subscription to channel

---

typescript/ws-protocol-examples/package.json
typescript/ws-protocol-examples/src/examples/mcap-play.ts

Added support for flatbuffer schemas in `mcap-play`.
None
We were only base64-encoding data for protobuf schemas, but needed to do this for flatbuffer as well. Added an error message to ensure we don't get this wrong for any future encodings, but skip the unknown encoding.

mcap-play: fix flatbuffer schema encoding

---

.github/workflows/ci.yml
typescript/ws-protocol-examples/package.json

Remove support for node 16.x
None
Node 16 is EOL and not supported anymore. This PR removes the node 16.x CI check and requires at least node 18 to run the `@foxglove/ws-protocol-examples` scripts.
See also https://github.com/foxglove/ws-protocol/pull/776#issuecomment-2228205157

remove support for node 16.x

---

cpp/foxglove-websocket/include/foxglove/websocket/server_interface.hpp
cpp/foxglove-websocket/include/foxglove/websocket/websocket_server.hpp
docs/spec.md
python/src/foxglove_websocket/server/__init__.py
python/src/foxglove_websocket/types.py
python/tests/test_server.py
typescript/ws-protocol-examples/src/examples/service-server.ts
typescript/ws-protocol/src/FoxgloveClient.ts
typescript/ws-protocol/src/FoxgloveServer.ts
typescript/ws-protocol/src/types.ts

Add support for clearing previously sent status messages
None
Adds the `removeStatus` operation which can be used to clear a previously sent status message. To identify which status message shall be cleared, a `id` field has been added to the status message.
Adapted implementations:

Add support for clearing previously sent status messages

---

cpp/dev.Dockerfile
cpp/foxglove-websocket/conanfile.py
cpp/foxglove-websocket/include/foxglove/websocket/websocket_server.hpp

Cpp: Fix incorrect exception being caught, fix docker warnings #796
None
- Fixes incorrect exception being caught (noticed that in https://github.com/foxglove/ros-foxglove-bridge/pull/307/commits/44abb8d6eaae72502067d106d6a01555d566224e)
- Fix docker warnings (`WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 24)`)
- ~Bumps conan recipe version~

Cpp: Fix incorrect exception being caught, fix docker warnings

---

cpp/dev.Dockerfile
cpp/foxglove-websocket/CMakeLists.txt

None
None
Only enable all warnings for CI builds
Motivation: https://github.com/conan-io/conan-center-index/pull/24761#pullrequestreview-2208180113

Only treat warnings as errors for CI builds

---

cpp/foxglove-websocket/include/foxglove/websocket/websocket_server.hpp

Guarantees that action handlers in C++ ws server are called after the action has been applied.
https://github.com/orgs/foxglove/discussions/1049
In C++ server, handlers for below events are called before the internal states are fully updated:
* subscribe
* unsubscribe
* client advertise
* client unadvertise
* subscribe connection graph
As a consequence, some user behavior does not work as expected, such as calling `sendMessage()` for messages of the requested topic inside of subscription handler. When subscription handler is called, the internal state does not recognize the requested topic as subscribed, and `sendMessage()` filters out this unsubscribed topic.
This seems to be a bug rather than a spec, because typescript and python server implementations calls listener/emit event after …

call action handlers after action, in c++ server

---

.github/dependabot.yml

We no longer depend on these packages.

Remove typescript-eslint dependabot group

---

cpp/foxglove-websocket/include/foxglove/websocket/common.hpp
cpp/foxglove-websocket/include/foxglove/websocket/websocket_client.hpp
cpp/foxglove-websocket/include/foxglove/websocket/websocket_server.hpp

C++ server/client: add missing implementations for client advertised schema / schema encoding
* Issue #875 (Initial discussions are here)
* Liner Ticket FG-9447 (though I can't access to it)
Although foxglove ws protocol allow client to advertise complete schema definition string as well as schema name, current C++ implementation lacks such fields. Particularly:
* `ClientAdvertisement` struct lacks `schemaEncoding` field,
* `ClientAdvertisement` struct has `schema` field, but it is never populated (websocket server does not read schema or schema encoding to json)
* websocket client is does not serialize schema or schema encoding to json
This PR resolves above problems, and additionally since this is breaking change from unimplemented to implemented, types are decided as following:
* …

C++: add missing implementations for client advertised schema/encoding

---

cpp/examples/conanfile.py
cpp/foxglove-websocket/conanfile.py

Bumping version number
iirc this doesn't actually matter since these files are not exported, but good to have it match the tagged version

Bump cpp to v1.4.0

---

docs/spec.md

clarify that "log time" is the same as "receive time"
https://github.com/foxglove/docs/pull/498
work towards standardizing on "log time" as the default nomenclature

make log time and receive time synonyms

---

test-client-web-app/package.json
yarn.lock

None
None
This bumps webpack-dev-server to update `path-to-regexp` and `cookie`, which have dependabot alerts but were not able to be updated auotmatically.
The dev server is used by `test-client-web-app`.

Bump webpack-dev-server 

---

typescript/ws-protocol/src/FoxgloveClient.ts

None
None
This removes the "supported subprotocol" check performed after the handshake, instead relying on the underlying websocket client to advertise the correct subprotocol.
The `FoxgloveClient` already accepts a websocket client (`IWebSocket`), which is free to choose its advertised subprotocols. This change would allow it to be extended with backwards-compatible subprotocols (for example, v2).
This change is not breaking as long as existing clients are advertising the correct subprotocol.

[typescript] Allow client to understand other subprotocols

---

typescript/ws-protocol/package.json

Remove the explicit check for a supported subprotocol in `FoxgloveClient`. Rely on the WS client to advertise the correct value and the handshake to enforce it.
None
Version bump for #916

Bump typescript ws-protocol to 0.7.5

---

cpp/foxglove-websocket/src/serialization.cpp

cpp: Add parameter type float64 & float64_array for floating point values
From https://github.com/foxglove/ws-protocol/pull/519:
> Some languages, such as JavaScript, do not differentiate between integers and floating point numbers. The `float64` and `float64_array` types were added to avoid ambiguity by informing the client (or the server) that the value is a floating point number, or an array of it, respectively.
On the foxglove_bridge side this has been implemented in https://github.com/foxglove/ros-foxglove-bridge/pull/256 but that change has apparently never found its way to this repo. This PR applies that change to this repo.

cpp: specify param type for double / double array parameters

---

typescript/ws-protocol-examples/src/examples/service-client.ts
typescript/ws-protocol-examples/src/examples/service-server.ts
typescript/ws-protocol-examples/src/examples/simple-client.ts
typescript/ws-protocol/src/FoxgloveClient.ts
typescript/ws-protocol/src/FoxgloveServer.test.ts
typescript/ws-protocol/src/FoxgloveServer.ts
typescript/ws-protocol/src/parse.ts
typescript/ws-protocol/src/types.ts

Typescript: Use ArrayBufferView instead of DataView for data types.
None
- 65323c5dcc6dc8228bcfc55485984ef162d927e1 changes the typescript client's `onmessage` handler to accept messages of type `ArrayBufferView` (e.g. Uint8Arrays). This gives more flexibility when implementing a custom `IWebSocket` source.
- 6382cea5da3f40ad98c898a651bbd3b28b39793b changes the type of `data` message fields from `DataView` to `ArrayBufferView`. This is a breaking change, but makes the API easier to use.

Typescript: Use ArrayBufferView instead of DataView for data types.

---

README.md
cpp/README.md
cpp/examples/conanfile.py
cpp/foxglove-websocket/conanfile.py
python/README.md
python/setup.cfg

This adds deprecation notices to the README, and to C++ and Python packages, which are being replaced by the Foxglove SDK (https://github.com/foxglove/foxglove-sdk).
This bumps the version numbers of C++ and Python packages, so that we can publish a patch release with deprecation notices on those repositories.

Add deprecation notices

---

.github/workflows/ci.yml

None
None
PyPI publishing is failing. See https://github.com/foxglove/foxglove-sdk/pull/158:
> Running a publish to TestPyPI immediately followed by a publish to the "real" PyPI triggered an error due to a file already existing. The workaround recommended in https://github.com/pypa/gh-action-pypi-publish/issues/283#issuecomment-2499296440 is to set attestations: false on the TestPyPI publish.
This removes attestations from the Test publish step as described above.
I'll either need to tag v0.1.5 as the next release, or move the v0.1.4 tag which I created a little while ago.

Skip attestations for test publish
